name: Build (OS/2)

on: [push, pull_request]

jobs:
  os2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: open-watcom/setup-watcom@v0
      - name: Build library and player
        run: |
          cd os2 && wmake
          cd ..
      - name: distclean
        run: |
          cd os2 && wmake distclean
          cd ..
